name: Deploy to gh-pages
on: [push]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        
      - name: Replace API Key
        run: sed -i "s/YOUR_API_KEY_HERE/${{ secrets.OPENWEATHER_API_KEY }}/g" script.js

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./
          publish_branch: gh-pages
